version: "3.8"
services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./backend/data.db:/app/data.db
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./data.db
      - STORAGE_BACKEND=local
      - LOCAL_STORAGE_PATH=/tmp/pmg_storage
      - MOCK_MODE=1
    depends_on:
      - redis

  worker:
    build: ./backend
    command: celery -A tasks.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./data.db
      - MOCK_MODE=1
    depends_on:
      - redis
      - backend